# Generated by Django 5.2.6 on 2025-09-25 22:49

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('sex', models.CharField(choices=[('F', 'Female'), ('M', 'Male'), ('O', 'Other'), ('N', 'Prefer not to say')], default='N', max_length=1)),
                ('age', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(120)])),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('country', models.CharField(max_length=64)),
                ('favourite_genre1', models.CharField(blank=True, choices=[('Action', 'Action'), ('Adventure', 'Adventure'), ('Animation', 'Animation'), ('Comedy', 'Comedy'), ('Crime', 'Crime'), ('Drama', 'Drama'), ('Family', 'Family'), ('Fantasy', 'Fantasy'), ('History', 'History'), ('Horror', 'Horror'), ('Music', 'Music'), ('Mystery', 'Mystery'), ('Romance', 'Romance'), ('Science Fiction', 'Science Fiction'), ('Thriller', 'Thriller'), ('War', 'War'), ('Western', 'Western')], max_length=32)),
                ('favourite_genre2', models.CharField(blank=True, choices=[('Action', 'Action'), ('Adventure', 'Adventure'), ('Animation', 'Animation'), ('Comedy', 'Comedy'), ('Crime', 'Crime'), ('Drama', 'Drama'), ('Family', 'Family'), ('Fantasy', 'Fantasy'), ('History', 'History'), ('Horror', 'Horror'), ('Music', 'Music'), ('Mystery', 'Mystery'), ('Romance', 'Romance'), ('Science Fiction', 'Science Fiction'), ('Thriller', 'Thriller'), ('War', 'War'), ('Western', 'Western')], max_length=32)),
                ('liked_g1_tmdb_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('liked_g1_title', models.CharField(blank=True, max_length=300)),
                ('liked_g2_tmdb_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('liked_g2_title', models.CharField(blank=True, max_length=300)),
                ('language', models.CharField(blank=True, help_text='e.g., en, hi, kn', max_length=16)),
                ('timezone', models.CharField(blank=True, help_text='e.g., America/New_York', max_length=64)),
                ('onboarding_complete', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmdb_id', models.IntegerField(db_index=True)),
                ('status', models.CharField(choices=[('LIKE', 'Like'), ('DISLIKE', 'Dislike'), ('WATCH_LATER', 'Watch Later'), ('WATCHED', 'Watched')], db_index=True, max_length=12)),
                ('rating', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('source', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'status'], name='recom_sys_a_user_id_c2ffc7_idx'), models.Index(fields=['tmdb_id', 'status'], name='recom_sys_a_tmdb_id_ad14ef_idx'), models.Index(fields=['-updated_at'], name='recom_sys_a_updated_2e1c0d_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'tmdb_id'), name='uniq_user_movie')],
            },
        ),
    ]
