# Generated by Django 5.2.7 on 2025-10-12 00:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recom_sys_app", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GroupSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "group_code",
                    models.CharField(db_index=True, max_length=8, unique=True),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_groups",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "group_sessions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="GroupMember",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "role",
                    models.CharField(
                        choices=[("CREATOR", "Creator"), ("MEMBER", "Member")],
                        default="MEMBER",
                        max_length=10,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="group_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "group_session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="recom_sys_app.groupsession",
                    ),
                ),
            ],
            options={
                "db_table": "group_members",
                "ordering": ["joined_at"],
            },
        ),
        migrations.AddIndex(
            model_name="groupsession",
            index=models.Index(
                fields=["group_code"], name="group_sessi_group_c_47ffe1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="groupsession",
            index=models.Index(
                fields=["creator", "-created_at"], name="group_sessi_creator_dbfce3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="groupmember",
            index=models.Index(
                fields=["group_session", "is_active"],
                name="group_membe_group_s_47a7c8_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="groupmember",
            index=models.Index(
                fields=["user", "is_active"], name="group_membe_user_id_0e6ce0_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="groupmember",
            constraint=models.UniqueConstraint(
                fields=("group_session", "user"), name="uniq_group_user"
            ),
        ),
    ]
