# Generated by Django 5.2.7 on 2025-10-17 19:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recom_sys_app', '0002_groupsession_groupmember_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupMatch',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tmdb_id', models.IntegerField(db_index=True)),
                ('movie_title', models.CharField(blank=True, max_length=300)),
                ('matched_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('group_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='recom_sys_app.groupsession')),
            ],
            options={
                'db_table': 'group_matches',
                'indexes': [models.Index(fields=['group_session', '-matched_at'], name='group_match_group_s_7aa0d8_idx'), models.Index(fields=['tmdb_id'], name='group_match_tmdb_id_982fba_idx')],
                'constraints': [models.UniqueConstraint(fields=('group_session', 'tmdb_id'), name='uniq_group_match')],
            },
        ),
        migrations.CreateModel(
            name='GroupSwipe',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tmdb_id', models.IntegerField(db_index=True)),
                ('action', models.CharField(choices=[('LIKE', 'Like'), ('DISLIKE', 'Dislike'), ('SUPER_LIKE', 'Super Like')], max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('group_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swipes', to='recom_sys_app.groupsession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_swipes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'group_swipes',
                'indexes': [models.Index(fields=['group_session', 'tmdb_id'], name='group_swipe_group_s_e7d146_idx'), models.Index(fields=['user', 'action'], name='group_swipe_user_id_b3c4de_idx'), models.Index(fields=['-created_at'], name='group_swipe_created_8875eb_idx')],
                'constraints': [models.UniqueConstraint(fields=('group_session', 'user', 'tmdb_id'), name='uniq_group_user_movie_swipe')],
            },
        ),
    ]
