# Generated by Django 5.2.7 on 2025-10-28 14:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recom_sys_app", "0003_groupmatch_groupswipe"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GroupChatMessage",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "group_session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_messages",
                        to="recom_sys_app.groupsession",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "group_chat_messages",
                "ordering": ["created_at"],
                "indexes": [
                    models.Index(
                        fields=["group_session", "created_at"],
                        name="group_chat__group_s_50bb59_idx",
                    ),
                    models.Index(
                        fields=["user", "-created_at"],
                        name="group_chat__user_id_7e348a_idx",
                    ),
                ],
            },
        ),
    ]
