# Generated by Django 5.2.7 on 2025-11-07 23:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recom_sys_app", "0006_alter_groupsession_group_code"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="groupsession",
            name="community_key",
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="groupsession",
            name="kind",
            field=models.CharField(
                choices=[("PRIVATE", "Private"), ("COMMUNITY", "Community")],
                db_index=True,
                default="PRIVATE",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="groupsession",
            name="group_code",
            field=models.CharField(db_index=True, max_length=32, unique=True),
        ),
        migrations.AddIndex(
            model_name="groupsession",
            index=models.Index(
                fields=["kind", "community_key"], name="group_sessi_kind_3d9e1e_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="groupsession",
            constraint=models.UniqueConstraint(
                condition=models.Q(("kind", "COMMUNITY")),
                fields=("kind", "community_key"),
                name="uniq_community_key_when_community",
            ),
        ),
    ]
