# Generated by Django 5.2.7 on 2025-12-02 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recom_sys_app", "0007_groupsession_community_key_groupsession_kind_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="interaction",
            name="status",
            field=models.CharField(
                choices=[
                    ("LIKE", "Like"),
                    ("DISLIKE", "Dislike"),
                    ("WATCH_LATER", "Watch Later"),
                    ("WATCHED", "Watched"),
                    ("WATCHED_LIKED", "Watched & Liked"),
                    ("WATCHED_DISLIKED", "Watched & Disliked"),
                ],
                db_index=True,
                max_length=20,
            ),
        ),
    ]
