# Generated by Django 5.2.7 on 2025-12-02 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recom_sys_app", "0008_add_watched_liked_disliked_statuses"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="profile_image",
            field=models.ImageField(
                blank=True,
                help_text="Upload a profile picture",
                null=True,
                upload_to="profile_images/",
            ),
        ),
    ]
