# Generated by Django 5.2.7 on 2025-12-14 04:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recom_sys_app", "0009_add_profile_image"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "genre_preferences",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Genre preference scores (0.0-1.0) based on user interactions",
                    ),
                ),
                (
                    "preferred_actors",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of preferred actor TMDB IDs",
                    ),
                ),
                (
                    "preferred_directors",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of preferred director TMDB IDs",
                    ),
                ),
                (
                    "average_rating_given",
                    models.FloatField(
                        blank=True,
                        help_text="Average rating given by user (1-10 scale)",
                        null=True,
                    ),
                ),
                ("total_interactions", models.IntegerField(db_index=True, default=0)),
                ("total_likes", models.IntegerField(default=0)),
                ("total_dislikes", models.IntegerField(default=0)),
                ("last_updated", models.DateTimeField(auto_now=True, db_index=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="preferences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "user_preferences",
                "ordering": ["-last_updated"],
                "indexes": [
                    models.Index(
                        fields=["user", "-last_updated"],
                        name="user_prefer_user_id_26fb75_idx",
                    ),
                    models.Index(
                        fields=["total_interactions"],
                        name="user_prefer_total_i_8bd967_idx",
                    ),
                ],
            },
        ),
    ]
