# Generated by Django 5.2 on 2025-09-18 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tmdb_id", models.IntegerField(unique=True)),
                ("title", models.CharField(max_length=255)),
                ("overview", models.TextField(blank=True)),
                ("release_date", models.DateField(blank=True, null=True)),
                ("runtime", models.IntegerField(blank=True, null=True)),
                ("vote_average", models.FloatField(default=0.0)),
                ("vote_count", models.IntegerField(default=0)),
                ("popularity", models.FloatField(default=0.0)),
                ("poster_path", models.CharField(blank=True, max_length=255)),
                ("backdrop_path", models.CharField(blank=True, max_length=255)),
                ("genres", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-popularity", "-vote_average"],
            },
        ),
    ]
